title: Apache Kylin - MOLAP queries for Hadoop
title_suffix: Apache Kylin # This is appended to every page title on the site 

email: tdunning@apache.org
permalink: pretty

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "/kyline" # Base URL when hosted on GitHub Pages (kylin repository under apache account)
noindex: 1
markdown: redcarpet
